import React from 'react';
import ReactToPdf from "react-to-pdf";

const ref = React.createRef();
const options = {
    orientation: 'landscape',
    unit: 'in',
    format: [4, 2]
};

const Blog = () => {
    return (
        <div className='max-w-screen-xl mx-auto px-5 space-y-10 py-10'>
            <div ref={ref}>
                <h2 className='font-bold text-4xl mb-4'>This is Blog title.</h2>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sequi non pariatur quas dolorem saepe, ab vel quos animi ratione neque, in deserunt cumque cum voluptate, sit officiis possimus consequuntur error. Magni asperiores totam, corporis iure soluta perspiciatis labore, modi quasi, neque libero eius fugit repellat dolores ducimus facere quidem culpa nobis qui beatae recusandae ab? Eveniet eius animi tempore corrupti nulla optio voluptas porro error unde nemo in iste accusantium culpa fugiat, aliquam rem, a sit ratione modi laudantium repudiandae iusto numquam molestiae necessitatibus? At officiis nam ab tempora? Rerum necessitatibus doloremque quam optio error? Aperiam nostrum nemo perferendis modi velit ea necessitatibus, dolorum, voluptate voluptas fuga accusantium animi aliquid temporibus nobis? Unde quaerat quae id at reprehenderit non? Sint consequatur ullam odio quaerat quis laboriosam delectus quod porro assumenda? Vero, ducimus, exercitationem aut blanditiis iure similique, esse quod sequi quam molestias necessitatibus eos facere? Expedita vitae officia esse libero temporibus tenetur facilis rerum voluptatibus explicabo exercitationem adipisci autem ipsam aliquid officiis quas harum, nesciunt odit omnis deleniti enim rem reiciendis qui quia! Voluptates rerum tempore vitae, sit inventore neque quod libero debitis modi ad tenetur magnam. Beatae mollitia, molestiae deserunt ullam aspernatur consequatur facere accusantium delectus? Autem labore inventore nemo. Mollitia amet cumque ex eaque animi eius explicabo dolor? Placeat possimus fugit nesciunt ea excepturi sequi, cumque voluptatem aliquid. Officia, odio ratione. Placeat quisquam, soluta temporibus cupiditate sequi minus culpa aliquid nobis veniam praesentium! Labore excepturi omnis itaque facere maiores doloremque id dolore ipsum? Ex quis at rerum cumque!</p>
                <ReactToPdf targetRef={ref} filename="firstBlog.pdf" options={options}>
                    {({ toPdf }) => (
                        <button onClick={toPdf} className='primary-btn mt-3'>Download PDF</button>
                    )}
                </ReactToPdf>
            </div>
            <div>
                <h2 className='font-bold text-4xl mb-4'>This is Blog title.</h2>
                <p>Velit, amet. Maiores voluptatum numquam deserunt, libero reiciendis quasi provident, officiis incidunt animi laboriosam esse ullam expedita velit magni impedit quod mollitia debitis quae aspernatur quidem! Eius laborum sint, ut saepe iusto ducimus perspiciatis, sapiente deserunt nemo voluptas magnam repellat aspernatur asperiores dolor consectetur? Maxime saepe blanditiis, suscipit pariatur sint tenetur officia illum culpa consectetur magnam incidunt dolores labore ipsum! Sapiente aliquam, amet incidunt nihil vitae delectus. Aperiam, reiciendis ratione aliquam eaque culpa beatae, similique a necessitatibus laboriosam, ipsa eveniet sint quidem porro. Minima quaerat praesentium quibusdam in magnam veniam autem illo adipisci officiis, maiores similique eius iste et laboriosam quam id ratione quo nostrum? Ipsam aspernatur cum quos suscipit neque fugit saepe? Voluptatum repellendus cum rerum minima illo nobis consequuntur, debitis unde harum qui accusantium similique, ipsam aliquam saepe recusandae assumenda fuga mollitia eaque. Eos quos quam totam dolore esse, id optio aspernatur adipisci accusantium fugit sit molestiae voluptates perspiciatis et dolorum hic. Illo, dolor commodi? Soluta rem dolore necessitatibus sed corrupti beatae hic totam sit! Natus, dolorum? Nisi autem, magnam quis dolor, ratione sapiente vitae, ab sequi nam possimus sit dignissimos error? Molestias vel laboriosam voluptatibus perferendis possimus optio recusandae harum cupiditate, nisi beatae, est, error iste? Explicabo dolor ipsam magnam accusamus, nisi vel, quo ipsa enim exercitationem ullam atque voluptate autem! Ad magni provident cupiditate recusandae ab eos adipisci fuga voluptatum, minus dicta pariatur aliquam, consequuntur corporis libero sed? Minus, repellendus sapiente necessitatibus ut excepturi odit aperiam non ea aut dolores cumque, quae praesentium. Velit, incidunt voluptate.</p>
                <button className='primary-btn mt-3'>Download PDF</button>
            </div>
            <div>
                <h2 className='font-bold text-4xl mb-4'>This is Blog title.</h2>
                <p>Numquam, cupiditate quam ea pariatur, veritatis vel excepturi modi, labore fugit eos quis odit amet quasi. Distinctio, id quis neque maxime libero nostrum voluptatum veritatis assumenda minus nihil quibusdam magni ex nobis aut, enim sint similique maiores aliquam! Odio officiis maiores numquam accusantium. Dolorum officia aspernatur, ex quae maxime corrupti possimus quasi nemo, distinctio, molestias perspiciatis in. Animi rem et aliquam sed quod fugiat voluptas? Ab, delectus sapiente! Ut eum labore doloribus voluptas aliquid voluptates aut magni, porro dolore dignissimos fugiat, officiis praesentium perferendis consequatur sint quo assumenda magnam eligendi esse aspernatur? Nemo maxime temporibus quam dolorem explicabo excepturi optio nihil saepe reiciendis reprehenderit rem eius quis, harum eligendi non perferendis aliquam magnam, repellendus sapiente provident aspernatur. Optio facilis eveniet dolorem aspernatur amet quo sapiente explicabo magni eaque, officiis impedit, illum nobis veniam voluptates earum deserunt, sit quia! Adipisci iste deleniti fugit dolores? Eos aliquid aut accusantium esse facilis sequi similique ratione hic consequuntur itaque repellendus omnis ullam quasi ipsum, vel error architecto. Quidem provident magni dolores sapiente, perspiciatis ipsa? Molestiae ipsa sapiente unde possimus libero neque laudantium et, non, magnam numquam dolores aperiam nobis laborum officiis voluptatem obcaecati totam ratione fugiat corporis quaerat, sint tempore incidunt. Mollitia, fugiat officia? Assumenda repellat eos ipsa saepe modi aspernatur ab. Amet in autem ipsum porro magni dicta repudiandae, est incidunt blanditiis, iusto voluptatem beatae nesciunt distinctio natus eius ratione delectus nemo? Debitis eaque fugit doloremque. Illo esse, excepturi fugiat perferendis, dolor est minima, repellat dignissimos soluta tempore cumque? Voluptate corporis sed explicabo.</p>
                <button className='primary-btn mt-3'>Download PDF</button>
            </div>
            <div>
                <h2 className='font-bold text-4xl mb-4'>This is Blog title.</h2>
                <p>Eos repudiandae qui non repellendus, numquam natus, quis repellat aliquam enim iste unde rem aperiam, autem et ex sint nisi incidunt? Ducimus sequi qui labore. Earum nihil magnam numquam ipsa, delectus doloribus ullam sit corporis consequatur tempora ad in perferendis quis accusamus nam voluptas error fugit recusandae incidunt, perspiciatis neque saepe veritatis? Ut quisquam labore asperiores aliquid perferendis pariatur, cum earum iure maiores, odio, vero doloremque alias nemo optio. Quod iste quaerat quos dolores facere, numquam at voluptatibus deleniti neque suscipit illum! Numquam aut atque necessitatibus, praesentium autem pariatur quo reiciendis laudantium debitis aliquid voluptatum ullam incidunt, eveniet, enim perspiciatis nostrum ducimus eaque quia cum explicabo placeat officia eius laborum error? Esse obcaecati labore a, tempora adipisci doloremque qui quod quisquam alias harum. Autem, molestias accusantium! Esse placeat recusandae labore fuga. Nulla dolorem officia quibusdam eaque nihil omnis, harum, laboriosam ad alias, inventore porro autem commodi sint earum reprehenderit ut et quasi molestiae! Provident quos soluta voluptatum rerum accusantium sit labore illum iure odit, laborum voluptas quam, quas molestiae in tempore tenetur quaerat, sequi iste. Aspernatur odit quam itaque vitae nostrum quasi officiis et quibusdam cupiditate dolore quaerat, quo nemo vero eaque ut velit officia? Voluptatibus ipsa porro animi ratione sint hic. Suscipit a nesciunt praesentium autem quia aperiam ullam ipsa unde assumenda maiores labore minima, vero quidem sint qui pariatur consequatur rerum inventore fugiat? Nisi labore, a consequuntur autem vero cupiditate ut excepturi rem quas voluptatem nulla deleniti? Repellat porro sit autem consequatur iste recusandae ex a soluta quibusdam.</p>
                <button className='primary-btn mt-3'>Download PDF</button>
            </div>
            <div>
                <h2 className='font-bold text-4xl mb-4'>This is Blog title.</h2>
                <p>Necessitatibus tempore quaerat similique fugiat ducimus alias atque officia ipsum vel, quibusdam velit dolores, autem amet iste voluptatem earum aut eum ipsa. Perspiciatis ullam tempore laborum excepturi velit cupiditate quia quos ipsum repellendus aut reprehenderit suscipit molestiae perferendis modi explicabo, quae officiis nihil quod commodi laboriosam aliquam esse beatae. Reiciendis dicta ipsa provident at saepe! Amet a facilis eligendi recusandae id expedita hic, aut nemo quam quibusdam, perferendis consequuntur doloremque architecto! Placeat nam doloribus ipsam quam perferendis a suscipit, debitis, aliquid neque nihil dolor labore commodi voluptas quod mollitia deserunt quae minus, corrupti accusamus aspernatur eos reprehenderit facilis? Voluptatem dicta quasi quaerat veritatis voluptatibus minus necessitatibus consectetur, assumenda fuga, mollitia ab? Qui mollitia et quas dolorum odit. Excepturi nihil id dicta, nam inventore debitis et reiciendis temporibus, earum quo fugit repudiandae deserunt laudantium nisi. Possimus quibusdam odit impedit illo ducimus sint laboriosam, nam rem quidem iste consequuntur voluptate labore error veritatis aspernatur sapiente omnis et accusantium non officia velit. Voluptatum tempora fugit asperiores obcaecati fugiat, ea est animi eius tenetur voluptate dolorum adipisci modi nostrum aut, maiores amet consequatur, eum soluta odit. Necessitatibus maxime exercitationem quia animi dolorum possimus mollitia hic illo ex, sed aspernatur voluptatem in? Et ipsum dolorem aperiam libero nobis accusantium doloribus neque dolore quam suscipit repudiandae ex ab veniam quidem excepturi quod, unde, nemo quibusdam voluptatem consequatur porro laudantium? Molestiae culpa voluptatum deleniti repellendus, incidunt cupiditate ducimus vel architecto hic corporis. Labore dolorum quo cupiditate! Illum nobis dolor repellendus expedita quasi soluta velit. Sapiente, ut rem!</p>
                <button className='primary-btn mt-3'>Download PDF</button>
            </div>
            <div>
                <h2 className='font-bold text-4xl mb-4'>This is Blog title.</h2>
                <p>Nostrum ad deleniti laudantium rem praesentium, porro repellendus in ex commodi inventore aliquam impedit, eveniet quibusdam sed fugiat animi dolorum. Velit asperiores perferendis nesciunt recusandae aliquam eaque amet id doloribus doloremque blanditiis, facere eligendi voluptatem quod sunt necessitatibus modi quos optio voluptas distinctio praesentium. Consequuntur voluptatibus corrupti possimus quas voluptatum! Officiis quos repudiandae temporibus autem magnam atque molestias exercitationem deleniti culpa, perferendis dignissimos laboriosam consectetur nostrum est odio unde! Ducimus, adipisci explicabo aliquid ipsam voluptate labore nulla rerum quo ad quam sunt vitae vero neque et alias impedit voluptas, sequi officia quis veniam, soluta nisi ipsa. Repudiandae, quis? Similique necessitatibus culpa, nostrum illo quos omnis, molestias qui enim temporibus possimus, accusantium eligendi? Veniam officia commodi quia possimus dolorem animi vitae cum, tempora, eaque optio eligendi laboriosam quos voluptate, iure unde? Ad provident odit atque officia ea, quidem eum laboriosam ratione explicabo, facere mollitia sed hic magni aut repellendus fugit culpa iusto. Facilis id at neque totam, facere quidem minima explicabo aliquam impedit dolorem consequuntur nulla repellendus aspernatur porro illum possimus, laboriosam consectetur quam rem asperiores perferendis. Odit molestiae inventore sapiente aut dicta ipsam, quo, minima autem architecto in neque consequatur. Totam voluptates corporis nisi dignissimos? Laboriosam temporibus doloribus veritatis atque autem maxime velit quod sint consequatur. At tempore laudantium incidunt eius mollitia, quidem ab velit qui, voluptate ducimus expedita repudiandae? Assumenda, numquam iusto? Tenetur, ut expedita aliquid explicabo quasi amet? At molestiae, cum provident quas soluta eveniet ratione cumque! Omnis minus harum obcaecati cupiditate dicta recusandae consectetur at, maiores ipsum.</p>
                <button className='primary-btn mt-3'>Download PDF</button>
            </div>
        </div>
    );
};

export default Blog;